const memberList = [
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '경민서',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/ohjisoo.png',
    name: '오지수',
    major: 'Computer Science 21',
    position: '백엔드장',
  },
  {
    memberImg: '/images/member/joyoungseo.png',
    name: '조영서',
    major: 'Computer Science 21',
    position: '회장',
  },
  {
    memberImg: '/images/member/shinjinyoung.png',
    name: '신진영',
    major: 'Computer Science 20',
    position: '부회장',
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '이지은',
    major: 'Computer Science 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '이채은',
    major: 'Computer Science 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '정서연',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '정지원',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '이해림',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '정나윤',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '최서윤',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '하예영',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '김수현',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '김진영',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '김혜림',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '류미성',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '윤서희',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '윤현서',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '장나리',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '정민주',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '주아정',
    major: 'Software Convergence 22',
    position: null,
  },
  {
    memberImg: '/images/member/kyungminseo.png',
    name: '하고은',
    major: 'Software Convergence 22',
    position: null,
  },
];

export default memberList;
